### PR TITLE
Use laravel `Http` facade for easy configuring request

### PR DESCRIPTION
**Pull request by lloricode**
- Set minimum latest patch support of laravel
- Drop support laravel 6 and 7

### CODE REVIEW

**Review by SebastiaanKloos — CHANGES_REQUESTED** [review]
I think we need to change the method names as you're using the HTTP facade instead of Guzzle. Also maybe it's better to first drop the old Laravel versions before merging this in.

What do you think @Cannonb4ll ?

**Comment by lloricode** [comment]
> I think we need to change the method names as you're using the HTTP facade instead of Guzzle. Also maybe it's better to first drop the old Laravel versions before merging this in.
> 
> What do you think @Cannonb4ll ?

Hi, already drop older laravel version, and the test is passed

**Comment by Cannonb4ll** [comment]
Would this be ready for review?

**Comment by lloricode** [comment]
> Would this be ready for review?

Hi, yes, but there a conflict with branch, will fix now

**Comment by lloricode** [comment]
hi @Cannonb4ll all test passed and this is ready to review, thank you

**Pull request closed without merging**
