### PR TITLE
Added more sensitive parameter names to blacklist

### PR DESCRIPTION
**Pull request by cbl**

### CODE REVIEW

**Comment by Cannonb4ll** [comment]
Can you also add `csrf_token`? @SebastiaanKloos @Glennmen If you have any other suggestions to blacklist for keys we do not want to hold let me know.

**Comment by cbl** [comment]
@Cannonb4ll `token` is added so `csrf_token` will be filtered.

**Comment by cbl** [comment]
Oh no that is not true, thought a parameter will be filtered when it contains any of the words in blacklist.

**Comment by Cannonb4ll** [comment]
What I meant was, the `csrf_token` is an input hidden in laravel applications with a key called `_token` which we want to filter out too.

**Comment by Glennmen** [comment]
Things like `email` or similar information? To avoid any privacy issues.

**Comment by cbl** [comment]
@Cannonb4ll Yes I know. I added this to the other pr:

https://github.com/LaraBug/LaraBug/blob/5a462a9821b7299e4a53acadcbbf89375e909014/src/LaraBug.php#L223-L227

By this we can add string like `*token*` or `*password*` to the blacklist. So `*token*` would also filter `csrf_token`.

**Comment by cbl** [comment]
> Things like `email` or similar information? To avoid any privacy issues.

I think `email` is something you might want to debug.

**Comment by Cannonb4ll** [comment]
@cbl I missed that one, yes, then you can use wildcards which is great.

The email and name values are a issue as well I recon, might want to obfuscate smartly before sending to larabug?

**Comment by cbl** [comment]
I think `email` and `name` is not something you want to filter. And if you want to filter it you have the option to do so. The reason I added parameters is because I it is usefull to see those values for debugging. You should never give access to the exceptions to anyone that should not have access to private data of your application anyway.

**Comment by Glennmen** [comment]
Why won't you want to filter it by default? What use does user information have for exception logging?
Problem is not access but sending that data to a third party, Larabug in this case.

From my experience with other exception tools, mainly ones for Android (Crashlytics), by default they never send user information unless you add it yourself.

**Comment by cbl** [comment]
Yes, you are right. This data should not be passed on to third parties by default. I will add this to the blacklist.

**Comment by Cannonb4ll** [comment]
@Glennmen We really need to fix those tests.

@cbl Can you replace `*username*` for `*name*`? Its more broad.

**Comment by Glennmen** [comment]
I will try to look into it but this workflow wasn't made by me. I only did it for the Larabug app.
But it shouldn't be blocking for this PR, I will fix it in a separate branch.

**Pull request merged**
