### PR TITLE
Added env variable for setting LaraBug server (for LaraBug maintainers)

### PR DESCRIPTION
**Pull request by SebastiaanKloos**

### CODE REVIEW

**Comment by Cannonb4ll** [comment]
Can you convert this to config() with the env var in that so config caching works?

**Comment by SebastiaanKloos** [comment]
> Can you convert this to config() with the env var in that so config caching works?

Yes!

**Comment by SebastiaanKloos** [comment]
@Cannonb4ll It's fixed!

**Comment by SebastiaanKloos** [comment]
@Cannonb4ll Thanks! 🙏

**Pull request merged**
