### PR TITLE
Add Support for Laravel 10

### PR DESCRIPTION
**Pull request by lloricode**
- Fix LaraBugHandler.php
- Add Github action test for laravel 10

### CODE REVIEW

**Review by SebastiaanKloos — COMMENTED** [review]
Maybe we can drop support for old PHP and Laravel versions in this PR. What do you think @Cannonb4ll ?

**Comment by lloricode** [comment]
> Maybe we can drop support for old PHP and Laravel versions in this PR. What do you think @Cannonb4ll ?

Yes, much better, to be as easy to maintain this package

**Comment by lloricode** [comment]
Closing, already done by @Cannonb4ll https://github.com/LaraBug/LaraBug/commit/01014a1bc912bad99b442615e5232f5c427affdf

**Comment by kovacevic-matija** [comment]
when will this be tagged?

**Comment by lloricode** [comment]
> when will this be tagged?

you can you this update by changin in conposer.json to

dev-master

**Pull request closed without merging**
