### PR TITLE
Travis to Github/Actions

### PR DESCRIPTION
**Pull request by nickurt**
Actions has now-days better integration with GitHub than Travis has, and is faster with workflows ..

### CODE REVIEW

**Comment by Cannonb4ll** [comment]
Awesome! I have not tried it before, how do I setup actions in the tab above?

**Comment by nickurt** [comment]
Should be automatic when you merge this pull-request, after that you can modify branch-restrictions here

https://github.com/LaraBug/LaraBug/settings/branches

**Comment by nickurt** [comment]
Yup, it's working.

Branch-permissions should look like this now

branch-permissions

**Comment by Cannonb4ll** [comment]
Cool!

**Comment by nickurt** [comment]
Yeah, when checked, GitHub Actions will run automatic by Pull Requests ;)

**Pull request merged**
